#!/bin/sh
# configure-dual-domain.sh - Configure isle-agent to respond to both .local and .vlan domains
#
# This script configures nginx to accept connections via both:
#   - hostname.local (mDNS advertised)
#   - hostname.vlan (DNS mapped by join protocol)
#
# Usage: configure-dual-domain.sh <hostname> [vlan-suffix]
#
# Example: configure-dual-domain.sh myserver
#          Results in: myserver.local and myserver.vlan

set -e

# Configuration
HOSTNAME="${1:-isle-agent}"
VLAN_SUFFIX="${2:-vlan}"
NGINX_CONF_DIR="/etc/nginx/conf.d"
SERVER_NAME_CONF="${NGINX_CONF_DIR}/server-names.conf"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_error() {
    echo -e "${RED}[✗]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[⚠]${NC} $1"
}

# Validate hostname
validate_hostname() {
    if [ -z "$HOSTNAME" ]; then
        log_error "Hostname cannot be empty"
        exit 1
    fi

    # Check for valid hostname format
    if ! echo "$HOSTNAME" | grep -qE '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'; then
        log_error "Invalid hostname format: $HOSTNAME"
        log_info "Hostname must contain only lowercase letters, numbers, and hyphens"
        exit 1
    fi

    log_success "Hostname validated: $HOSTNAME"
}

# Generate nginx server name configuration
generate_nginx_config() {
    log_info "Generating nginx server name configuration..."

    # Create conf.d directory if it doesn't exist
    mkdir -p "$NGINX_CONF_DIR"

    # Generate configuration file
    cat > "$SERVER_NAME_CONF" << EOF
# Isle Mesh Dual-Domain Configuration
# Auto-generated by configure-dual-domain.sh
# Allows nginx to respond to both .local and .vlan domains

# Map for dual domain support
map \$host \$isle_backend_host {
    default \$host;

    # Map both .local and .vlan to the same backend
    ${HOSTNAME}.local ${HOSTNAME};
    ${HOSTNAME}.${VLAN_SUFFIX} ${HOSTNAME};
}

# Server name wildcards
# This allows any upstream server block to use:
#   server_name ${HOSTNAME}.local ${HOSTNAME}.${VLAN_SUFFIX};

EOF

    log_success "Created server name configuration: $SERVER_NAME_CONF"
}

# Generate example nginx vhost configuration
generate_example_vhost() {
    local example_file="${NGINX_CONF_DIR}/example-vhost.conf.disabled"

    log_info "Generating example vhost configuration..."

    cat > "$example_file" << EOF
# Example virtual host configuration for dual-domain support
# To enable: mv example-vhost.conf.disabled example-vhost.conf

server {
    listen 80;
    listen [::]:80;

    # Respond to both .local and .vlan domains
    server_name ${HOSTNAME}.local ${HOSTNAME}.${VLAN_SUFFIX};

    # Root directory
    root /var/www/html;
    index index.html index.htm;

    # Logging
    access_log /var/log/nginx/${HOSTNAME}.access.log;
    error_log /var/log/nginx/${HOSTNAME}.error.log;

    # Default location
    location / {
        try_files \$uri \$uri/ =404;
    }

    # Health check endpoint
    location /health {
        access_log off;
        return 200 "OK\\n";
        add_header Content-Type text/plain;
    }

    # Example reverse proxy to backend service
    # location /app {
    #     proxy_pass http://backend-service:8080;
    #     proxy_set_header Host \$host;
    #     proxy_set_header X-Real-IP \$remote_addr;
    #     proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto \$scheme;
    # }
}

# HTTPS configuration (uncomment when you have certificates)
# server {
#     listen 443 ssl http2;
#     listen [::]:443 ssl http2;
#
#     server_name ${HOSTNAME}.local ${HOSTNAME}.${VLAN_SUFFIX};
#
#     ssl_certificate /etc/nginx/ssl/certs/${HOSTNAME}.crt;
#     ssl_certificate_key /etc/nginx/ssl/keys/${HOSTNAME}.key;
#
#     # SSL configuration
#     ssl_protocols TLSv1.2 TLSv1.3;
#     ssl_ciphers HIGH:!aNULL:!MD5;
#     ssl_prefer_server_ciphers on;
#
#     # Include same configuration as HTTP
#     include ${NGINX_CONF_DIR}/example-vhost.conf.disabled;
# }
EOF

    log_success "Created example vhost: $example_file"
    log_info "To enable: mv $example_file ${NGINX_CONF_DIR}/example-vhost.conf"
}

# Set container hostname
set_container_hostname() {
    log_info "Setting container hostname..."

    # Set hostname in container
    if command -v hostname >/dev/null 2>&1; then
        hostname "$HOSTNAME" 2>/dev/null || log_warning "Could not set hostname (may need to run as root)"
    fi

    # Update /etc/hostname if writable
    if [ -w /etc/hostname ]; then
        echo "$HOSTNAME" > /etc/hostname
        log_success "Updated /etc/hostname"
    else
        log_warning "/etc/hostname is not writable (this is normal in Docker)"
    fi

    # Update /etc/hosts
    if [ -w /etc/hosts ]; then
        # Remove any existing entries for this hostname
        sed -i "/${HOSTNAME}/d" /etc/hosts 2>/dev/null || true

        # Add new entries for both domains
        cat >> /etc/hosts << EOF

# Isle Mesh dual-domain entries
127.0.0.1 ${HOSTNAME}.local
127.0.0.1 ${HOSTNAME}.${VLAN_SUFFIX}
::1 ${HOSTNAME}.local
::1 ${HOSTNAME}.${VLAN_SUFFIX}
EOF
        log_success "Updated /etc/hosts with dual-domain entries"
    fi
}

# Update avahi configuration to use hostname
update_avahi_hostname() {
    local avahi_conf="/etc/avahi/avahi-daemon.conf"

    if [ ! -f "$avahi_conf" ]; then
        log_warning "Avahi config not found - skipping avahi hostname update"
        return 0
    fi

    log_info "Updating avahi hostname configuration..."

    # Update or add host-name in [server] section
    if grep -q "^host-name=" "$avahi_conf"; then
        sed -i "s/^host-name=.*/host-name=${HOSTNAME}/" "$avahi_conf"
    else
        # Add after [server] section
        sed -i "/^\[server\]/a host-name=${HOSTNAME}" "$avahi_conf"
    fi

    log_success "Updated avahi hostname to: $HOSTNAME"
}

# Create SSH configuration for dual-domain support
configure_ssh_dual_domain() {
    local sshd_config="/etc/ssh/sshd_config"

    if [ ! -f "$sshd_config" ]; then
        log_info "SSH not installed - skipping SSH configuration"
        return 0
    fi

    log_info "Configuring SSH for dual-domain support..."

    # SSH should work automatically with DNS, but we can add some optimizations
    if [ -w "$sshd_config" ]; then
        # Ensure UseDNS is set appropriately
        if grep -q "^UseDNS" "$sshd_config"; then
            sed -i "s/^UseDNS.*/UseDNS yes/" "$sshd_config"
        else
            echo "UseDNS yes" >> "$sshd_config"
        fi
        log_success "SSH configured for DNS resolution"
    else
        log_warning "Cannot write SSH config (this is normal in containers)"
    fi
}

# Generate summary
show_summary() {
    cat << EOF

${GREEN}╔═══════════════════════════════════════════════════════════════╗
║         Dual-Domain Configuration Complete                    ║
╚═══════════════════════════════════════════════════════════════╝${NC}

${BLUE}Configuration:${NC}
  Hostname:        ${HOSTNAME}
  .local domain:   ${HOSTNAME}.local
  .vlan domain:    ${HOSTNAME}.${VLAN_SUFFIX}

${BLUE}What Was Configured:${NC}
  ✓ Nginx server name configuration
  ✓ Example vhost with dual-domain support
  ✓ Container hostname
  ✓ Avahi mDNS hostname
  ✓ SSH DNS resolution

${BLUE}Next Steps:${NC}
  1. ${YELLOW}Restart nginx to apply changes${NC}
     nginx -t && nginx -s reload

  2. ${YELLOW}Verify mDNS is advertising .local domain${NC}
     avahi-browse -a -t

  3. ${YELLOW}Test .local domain access${NC}
     curl http://${HOSTNAME}.local

  4. ${YELLOW}Wait for join protocol to create .vlan mapping${NC}
     (Happens automatically within 30 seconds on the router)

  5. ${YELLOW}Test .vlan domain access${NC}
     curl http://${HOSTNAME}.${VLAN_SUFFIX}

${BLUE}Files Created:${NC}
  • ${SERVER_NAME_CONF}
  • ${NGINX_CONF_DIR}/example-vhost.conf.disabled

${BLUE}Include in your nginx vhosts:${NC}
  ${YELLOW}server_name ${HOSTNAME}.local ${HOSTNAME}.${VLAN_SUFFIX};${NC}

${GREEN}Agent is ready for dual-domain operation!${NC}

EOF
}

# Main function
main() {
    echo ""
    log_info "Isle Agent Dual-Domain Configuration"
    echo ""

    validate_hostname
    generate_nginx_config
    generate_example_vhost
    set_container_hostname
    update_avahi_hostname
    configure_ssh_dual_domain

    show_summary
}

main "$@"
