#!/usr/bin/env bash
# install-node-services.sh — set up the plug-and-play node services after an isle
# install, in one step: (1) a system CLI entry point so root/udev can run `isle`,
# (2) boot self-recovery, (3) cable hotplug. Idempotent; safe on core and remote.
# Run with sudo.
set -euo pipefail
[[ ${EUID:-$(id -u)} -eq 0 ]] || { echo "Run with sudo: sudo bash $0" >&2; exit 1; }
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 1) System CLI entry point. npm-link installs already put /usr/local/bin/isle; a
#    user-space install (~/.local/bin/isle) is NOT reachable by sudo/udev — bridge it
#    with a wrapper that pins the node + index.js paths.
ensure_system_cli() {
  local idx="$ROOT/isle-cli/index.js"
  [[ -f "$idx" ]] || { echo "  ! isle-cli/index.js not found under $ROOT — skipping wrapper"; return 0; }
  if [[ -e /usr/local/bin/isle ]] && /usr/local/bin/isle help >/dev/null 2>&1; then
    echo "  ✓ system 'isle' already works (/usr/local/bin/isle)"; return 0
  fi
  local node=""
  node="$(command -v node 2>/dev/null || true)"
  [[ -z "$node" && -n "${SUDO_USER:-}" ]] && node="$(sudo -u "$SUDO_USER" bash -lc 'command -v node' 2>/dev/null || true)"
  [[ -n "$node" ]] || { echo "  ! node not found — install Node.js, then re-run"; return 1; }
  node="$(readlink -f "$node")"
  cat > /usr/local/bin/isle <<EOF
#!/bin/sh
# Isle-Mesh system entry point (generated by install-node-services.sh).
exec "$node" "$idx" "\$@"
EOF
  chmod +x /usr/local/bin/isle
  echo "  ✓ installed system 'isle' wrapper → $node $idx"
}

echo "==> Isle node services"
echo "[1/3] system CLI entry point"; ensure_system_cli || true
echo "[2/3] boot self-recovery";     [[ -f "$ROOT/install-boot-persistence.sh" ]] && bash "$ROOT/install-boot-persistence.sh" || echo "  (installer absent — skipped)"
echo "[3/3] cable hotplug";          [[ -f "$ROOT/install-hotplug.sh" ]] && bash "$ROOT/install-hotplug.sh" || echo "  (installer absent — skipped)"
echo "==> Node services ready: 'isle' works under sudo, the isle self-recovers on boot,"
echo "    and a plugged-in cable auto-connects (while discovery mode is on)."
