#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$ROOT_DIR/dist"
OUT="$OUT_DIR/router-init.sh"

mkdir -p "$OUT_DIR"

{
  cat <<'HDR'
#!/usr/bin/env bash
# router-init.sh (bundled) — generated by pack.sh
# Edit sources under router-init-lib/ and router-init.main.sh
# -----------------------------------------------------------------------------
set -euo pipefail
BUNDLED_MODE=1
HDR

  echo
  echo "### ===== BEGIN LIBS ====="
  echo

  # Bundle libraries in sorted order to honor 00-,10-,… prefixes
  for f in "$ROOT_DIR"/router-init-lib/[0-9][0-9]-*.sh; do
    echo "# --- $(basename "$f") ---"
    cat "$f"
    echo
  done

  echo "### ===== END LIBS ====="
  echo

  # Main last
  echo "# --- router-init.main.sh ---"
  cat "$ROOT_DIR/router-init.main.sh"
} > "$OUT"

chmod +x "$OUT"
echo "Built: $OUT"
