#!/usr/bin/env bash

#############################################################################
# Configure Isle Join Protocol Service on OpenWRT Router
#
# This script deploys and configures the isle-join-protocol service which:
#   - Discovers devices via mDNS/avahi (.local domains)
#   - Automatically creates .vlan domain mappings
#   - Updates dnsmasq for DNS resolution
#   - Monitors for new devices joining the network
#
# Usage: ./configure-join-protocol.sh --isle-name <name> --vlan-id <id>
#############################################################################

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Source common libraries
source "$SCRIPT_DIR/../lib/common-log.sh"
source "$SCRIPT_DIR/../lib/common-utils.sh"

# Configuration
ISLE_NAME="${ISLE_NAME:-my-isle}"
VLAN_ID="${VLAN_ID:-10}"
ROUTER_IP="${ROUTER_IP:-192.168.1.1}"
ROUTER_USER="${ROUTER_USER:-root}"
SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

# Parse arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --isle-name)
                ISLE_NAME="$2"
                shift 2
                ;;
            --vlan-id)
                VLAN_ID="$2"
                shift 2
                ;;
            --router-ip)
                ROUTER_IP="$2"
                shift 2
                ;;
            -h|--help)
                cat << EOF
Configure Isle Join Protocol Service

Usage: $0 --isle-name <name> --vlan-id <id> [options]

Options:
  --isle-name NAME    Isle name
  --vlan-id ID        VLAN ID
  --router-ip IP      Router IP (default: 192.168.1.1)
  -h, --help          Show this help

Description:
  Deploys the isle-join-protocol service to the OpenWRT router.
  This service discovers devices via mDNS and creates .vlan domain mappings.

EOF
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done
}

# Create the join protocol service script
create_join_protocol_service() {
    cat << 'EOF'
#!/bin/sh /etc/rc.common
# Isle Join Protocol Service
# Discovers .local domains via mDNS and creates .vlan mappings

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/isle-join-protocol
PIDFILE=/var/run/isle-join-protocol.pid

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param pidfile "$PIDFILE"
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    [ -f "$PIDFILE" ] && kill $(cat "$PIDFILE") 2>/dev/null
}
EOF
}

# Create the join protocol daemon script
create_join_protocol_daemon() {
    cat << 'DAEMON_EOF'
#!/bin/sh
# isle-join-protocol daemon
# Discovers mDNS .local domains and creates .vlan DNS entries

ISLE_NAME="$ISLE_NAME"
VLAN_ID="$VLAN_ID"
DNSMASQ_CONF="/etc/dnsmasq.d/isle-vlan-domains.conf"
DISCOVERY_INTERVAL=30
PIDFILE="/var/run/isle-join-protocol.pid"

# Logging functions
log_info() {
    logger -t isle-join-protocol -p info "$1"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] $1"
}

log_error() {
    logger -t isle-join-protocol -p err "$1"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] $1" >&2
}

# Write PID file
echo $$ > "$PIDFILE"

# Ensure dnsmasq.d directory exists
mkdir -p /etc/dnsmasq.d

# Initialize the vlan domains config file
initialize_config() {
    cat > "$DNSMASQ_CONF" << 'EOF'
# Isle Mesh .vlan Domain Mappings
# Auto-generated by isle-join-protocol
# Do not edit manually - changes will be overwritten

EOF
    log_info "Initialized DNS configuration file"
}

# Discover mDNS domains and extract hostname and IP
discover_domains() {
    local tmpfile="/tmp/avahi-browse-output.$$"

    # Run avahi-browse with timeout to get all services
    # -a: all services, -t: terminate after cache dump, -r: resolve
    timeout 10 avahi-browse -a -t -r 2>/dev/null > "$tmpfile" || true

    # Parse the output to extract hostname and IP pairs
    # Format: hostname=<name>.local, address=[<ip>]
    local discovered=""

    while IFS= read -r line; do
        # Look for hostname lines
        if echo "$line" | grep -q "hostname = \[.*\.local\]"; then
            current_hostname=$(echo "$line" | grep -oP '\[\K[^\]]+' | sed 's/\.local$//')
        fi

        # Look for address lines
        if echo "$line" | grep -q "address = \[.*\]" && [ -n "$current_hostname" ]; then
            current_ip=$(echo "$line" | grep -oP '\[\K[^\]]+')

            # Validate it's in our VLAN subnet
            if echo "$current_ip" | grep -q "^10\.${VLAN_ID}\."; then
                discovered="${discovered}${current_hostname}|${current_ip}\n"
            fi
            current_hostname=""
        fi
    done < "$tmpfile"

    rm -f "$tmpfile"
    echo -e "$discovered"
}

# Update dnsmasq configuration with discovered domains
update_dns_config() {
    local domains="$1"
    local tmpconf="/tmp/isle-vlan-domains.conf.$$"

    # Start with header
    cat > "$tmpconf" << 'EOF'
# Isle Mesh .vlan Domain Mappings
# Auto-generated by isle-join-protocol
# Do not edit manually - changes will be overwritten

EOF

    # Add each domain mapping
    echo -e "$domains" | while IFS='|' read -r hostname ip; do
        [ -z "$hostname" ] && continue
        [ -z "$ip" ] && continue

        # Create both .local and .vlan mappings pointing to same IP
        echo "address=/${hostname}.local/${ip}" >> "$tmpconf"
        echo "address=/${hostname}.vlan/${ip}" >> "$tmpconf"

        log_info "Mapped: ${hostname}.local -> ${hostname}.vlan (${ip})"
    done

    # Only update if content changed
    if ! cmp -s "$tmpconf" "$DNSMASQ_CONF" 2>/dev/null; then
        mv "$tmpconf" "$DNSMASQ_CONF"

        # Reload dnsmasq to apply changes
        /etc/init.d/dnsmasq reload
        log_info "DNS configuration updated and dnsmasq reloaded"
    else
        rm -f "$tmpconf"
    fi
}

# Main discovery loop
main_loop() {
    log_info "Isle Join Protocol daemon started (VLAN $VLAN_ID)"

    initialize_config

    while true; do
        log_info "Scanning for mDNS .local domains..."

        local discovered_domains
        discovered_domains=$(discover_domains)

        if [ -n "$discovered_domains" ]; then
            local count=$(echo -e "$discovered_domains" | grep -c '|' || echo 0)
            log_info "Found $count device(s) in VLAN $VLAN_ID"
            update_dns_config "$discovered_domains"
        else
            log_info "No devices discovered in VLAN $VLAN_ID"
        fi

        # Wait before next scan
        sleep "$DISCOVERY_INTERVAL"
    done
}

# Handle termination
trap 'log_info "Shutting down..."; rm -f "$PIDFILE"; exit 0' TERM INT

# Start main loop
main_loop
DAEMON_EOF
}

# Deploy to router
deploy_to_router() {
    log_step "Deploying Join Protocol Service to Router"

    # Check connectivity
    if ! ping -c 1 -W 2 "$ROUTER_IP" &> /dev/null; then
        log_error "Router not reachable at $ROUTER_IP"
        exit 1
    fi

    # Create temporary directory for service files
    local tmpdir="/tmp/isle-join-protocol-deploy-$$"
    mkdir -p "$tmpdir"

    # Generate service files
    log_info "Generating service files..."
    create_join_protocol_service > "$tmpdir/isle-join-protocol.init"
    create_join_protocol_daemon > "$tmpdir/isle-join-protocol.sh"

    # Substitute variables in daemon script
    sed -i "s/\$ISLE_NAME/$ISLE_NAME/g" "$tmpdir/isle-join-protocol.sh"
    sed -i "s/\$VLAN_ID/$VLAN_ID/g" "$tmpdir/isle-join-protocol.sh"

    # Copy files to router
    log_info "Copying files to router..."

    scp $SSH_OPTS "$tmpdir/isle-join-protocol.init" \
        "${ROUTER_USER}@${ROUTER_IP}:/etc/init.d/isle-join-protocol" &>/dev/null

    scp $SSH_OPTS "$tmpdir/isle-join-protocol.sh" \
        "${ROUTER_USER}@${ROUTER_IP}:/usr/bin/isle-join-protocol" &>/dev/null

    # Set permissions and enable
    log_info "Configuring service on router..."
    ssh $SSH_OPTS "${ROUTER_USER}@${ROUTER_IP}" << REMOTE_EOF
chmod +x /etc/init.d/isle-join-protocol
chmod +x /usr/bin/isle-join-protocol

# Enable and start the service
/etc/init.d/isle-join-protocol enable
/etc/init.d/isle-join-protocol start

# Ensure dnsmasq is configured to read from dnsmasq.d
if ! grep -q "conf-dir=/etc/dnsmasq.d" /etc/dnsmasq.conf 2>/dev/null; then
    echo "conf-dir=/etc/dnsmasq.d" >> /etc/dnsmasq.conf
    /etc/init.d/dnsmasq restart
fi
REMOTE_EOF

    # Cleanup
    rm -rf "$tmpdir"

    log_success "Join protocol service deployed and started"
}

# Verify service is running
verify_service() {
    log_step "Verifying Join Protocol Service"

    local status
    status=$(ssh $SSH_OPTS "${ROUTER_USER}@${ROUTER_IP}" \
        "/etc/init.d/isle-join-protocol status" 2>/dev/null || echo "stopped")

    if echo "$status" | grep -q "running"; then
        log_success "Service is running"
    else
        log_warning "Service may not be running properly"
        log_info "Check logs with: ssh root@${ROUTER_IP} 'logread | grep isle-join-protocol'"
    fi
}

# Show completion message
show_completion() {
    cat << EOF

${GREEN}╔═══════════════════════════════════════════════════════════════╗
║           Isle Join Protocol Service Configured              ║
╚═══════════════════════════════════════════════════════════════╝${NC}

${BLUE}Configuration:${NC}
  Isle Name:         ${ISLE_NAME}
  VLAN ID:           ${VLAN_ID}
  Router IP:         ${ROUTER_IP}
  Discovery Interval: 30 seconds

${BLUE}What It Does:${NC}
  • Scans for mDNS .local domains every 30 seconds
  • Automatically creates .vlan domain mappings
  • Updates dnsmasq DNS configuration
  • Enables access via both .local and .vlan domains

${BLUE}Service Management:${NC}
  # Check status
  ssh root@${ROUTER_IP} '/etc/init.d/isle-join-protocol status'

  # View logs
  ssh root@${ROUTER_IP} 'logread | grep isle-join-protocol'

  # Restart service
  ssh root@${ROUTER_IP} '/etc/init.d/isle-join-protocol restart'

  # View DNS mappings
  ssh root@${ROUTER_IP} 'cat /etc/dnsmasq.d/isle-vlan-domains.conf'

${BLUE}Testing:${NC}
  1. Ensure an isle-agent is running and advertising .local domain
  2. Wait up to 30 seconds for discovery
  3. Check DNS: ${CYAN}nslookup hostname.vlan ${ROUTER_IP}${NC}
  4. Test access: ${CYAN}curl http://hostname.vlan${NC}

${BLUE}Next Steps:${NC}
  1. Ensure isle-agents are advertising mDNS
  2. Configure agents to respond to .vlan domains
  3. Verify DHCP and DNS resolution work together

${GREEN}Join protocol service is active and monitoring!${NC}

EOF
}

# Main function
main() {
    log_banner "Configure Isle Join Protocol"

    parse_args "$@"
    require_root

    log_info "Configuring join protocol for: ${ISLE_NAME} (VLAN ${VLAN_ID})"
    echo

    deploy_to_router
    verify_service
    show_completion

    log_success "Configuration complete!"
}

main "$@"
