#!/bin/bash
# Isle mDNS Sample Environment
# Manages hand-crafted demo/example environments

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the project root (parent of isle-cli)
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# Path to localhost-mdns directory
LOCALHOST_MDNS_DIR="$PROJECT_ROOT/mesh-prototypes/localhost-mdns"

# Check if localhost-mdns directory exists
if [ ! -d "$LOCALHOST_MDNS_DIR" ]; then
    echo "Error: localhost-mdns directory not found at $LOCALHOST_MDNS_DIR"
    exit 1
fi

# Change to localhost-mdns directory
cd "$LOCALHOST_MDNS_DIR" || exit 1

ACTION=${1:-help}
COMPOSE_FILE="docker-compose.lh-mdns.yml"

case $ACTION in
    up)
        echo "Starting localhost-mdns sample stack..."
        docker compose -f "$COMPOSE_FILE" up -d
        ;;
    down)
        echo "Stopping localhost-mdns sample stack..."
        docker compose -f "$COMPOSE_FILE" down
        ;;
    build)
        echo "Building localhost-mdns sample services..."
        docker compose -f "$COMPOSE_FILE" build
        ;;
    rebuild)
        echo "Rebuilding localhost-mdns sample..."
        docker compose -f "$COMPOSE_FILE" down
        docker compose -f "$COMPOSE_FILE" build
        docker compose -f "$COMPOSE_FILE" up -d
        ;;
    logs)
        SERVICE=${2:-}
        if [ -n "$SERVICE" ]; then
            echo "Viewing logs for $SERVICE..."
            docker compose -f "$COMPOSE_FILE" logs -f "$SERVICE"
        else
            echo "Viewing all localhost-mdns logs..."
            docker compose -f "$COMPOSE_FILE" logs -f
        fi
        ;;
    status)
        echo "localhost-mdns status:"
        docker compose -f "$COMPOSE_FILE" ps
        ;;
    restart)
        SERVICE=${2:-}
        if [ -n "$SERVICE" ]; then
            echo "Restarting $SERVICE..."
            docker compose -f "$COMPOSE_FILE" restart "$SERVICE"
        else
            echo "Restarting all services..."
            docker compose -f "$COMPOSE_FILE" restart
        fi
        ;;
    exec)
        SERVICE=${2:-backend}
        echo "Executing shell in $SERVICE..."
        docker compose -f "$COMPOSE_FILE" exec "$SERVICE" /bin/bash
        ;;
    help|*)
        echo -e "${BOLD}Isle mDNS Sample Environment${NC}"
        echo ""
        echo "Run hand-crafted demo environments for testing and learning."
        echo ""
        echo "╔═══════════════════════════════════════════════════════════════╗"
        echo "║                    ABOUT SAMPLES                              ║"
        echo "╚═══════════════════════════════════════════════════════════════╝"
        echo ""
        echo -e "Sample environments are ${YELLOW}hand-crafted example projects${NC} that demonstrate"
        echo -e "Isle Mesh concepts. They are ${YELLOW}NOT generated by the framework${NC} - they are"
        echo "pre-built examples for testing and learning."
        echo ""
        echo -e "Current location: ${CYAN}$PROJECT_ROOT/mesh-prototypes/localhost-mdns${NC}"
        echo ""
        echo "╔═══════════════════════════════════════════════════════════════╗"
        echo "║                    LIFECYCLE COMMANDS                         ║"
        echo "╚═══════════════════════════════════════════════════════════════╝"
        echo ""
        echo -e "${CYAN}isle mdns sample up${NC}"
        echo "    Start the localhost-mdns demo stack in detached mode."
        echo "    Starts: backend, frontend, and mesh proxy services."
        echo ""
        echo -e "${CYAN}isle mdns sample down${NC}"
        echo "    Stop the localhost-mdns demo stack."
        echo "    Stops all demo containers."
        echo ""
        echo -e "${CYAN}isle mdns sample restart [service]${NC}"
        echo "    Restart services."
        echo "    • No argument: restart all services"
        echo "    • With service name: restart specific service"
        echo ""
        echo -e "${CYAN}isle mdns sample status${NC}"
        echo "    Show running demo containers and their status."
        echo ""
        echo "╔═══════════════════════════════════════════════════════════════╗"
        echo "║                    BUILD COMMANDS                             ║"
        echo "╚═══════════════════════════════════════════════════════════════╝"
        echo ""
        echo -e "${CYAN}isle mdns sample build${NC}"
        echo "    Build demo service images without starting them."
        echo ""
        echo -e "${CYAN}isle mdns sample rebuild${NC}"
        echo "    Stop, rebuild, and restart the demo stack."
        echo "    Useful when you've modified demo source code."
        echo ""
        echo "╔═══════════════════════════════════════════════════════════════╗"
        echo "║                    MONITORING & DEBUG                         ║"
        echo "╚═══════════════════════════════════════════════════════════════╝"
        echo ""
        echo -e "${CYAN}isle mdns sample logs [service]${NC}"
        echo "    View and follow logs."
        echo "    • No argument: show logs from all services"
        echo "    • With service name: show logs from specific service"
        echo ""
        echo "    Example:"
        echo "      isle mdns sample logs              # All logs"
        echo "      isle mdns sample logs backend      # Backend only"
        echo ""
        echo -e "${CYAN}isle mdns sample exec [service]${NC}"
        echo "    Execute bash shell in a service container."
        echo "    Default service: backend"
        echo ""
        echo "    Example:"
        echo "      isle mdns sample exec              # Shell in backend"
        echo "      isle mdns sample exec frontend     # Shell in frontend"
        echo ""
        echo "╔═══════════════════════════════════════════════════════════════╗"
        echo "║                    DEMO SERVICES                              ║"
        echo "╚═══════════════════════════════════════════════════════════════╝"
        echo ""
        echo -e "${BOLD}backend${NC}     Backend service   (exposed on port 8100:8443)"
        echo -e "${BOLD}frontend${NC}    Frontend service  (exposed on port 8080:8443)"
        echo -e "${BOLD}proxy${NC}       Mesh proxy        (exposed on ports 443:443, 80:80)"
        echo ""
        echo "╔═══════════════════════════════════════════════════════════════╗"
        echo "║                    EXAMPLES                                   ║"
        echo "╚═══════════════════════════════════════════════════════════════╝"
        echo ""
        echo -e "${YELLOW}Start and test demo:${NC}"
        echo "  isle mdns sample up                 # Start all services"
        echo "  isle mdns sample status             # Check they're running"
        echo "  isle mdns sample logs               # Watch logs"
        echo ""
        echo -e "${YELLOW}Debug a service:${NC}"
        echo "  isle mdns sample logs backend       # Check backend logs"
        echo "  isle mdns sample exec backend       # Shell into container"
        echo "  isle mdns sample restart backend    # Restart it"
        echo ""
        echo -e "${YELLOW}Clean up:${NC}"
        echo "  isle mdns sample down               # Stop everything"
        echo ""
        echo -e "${YELLOW}Rebuild after changes:${NC}"
        echo "  isle mdns sample rebuild            # Stop, rebuild, start"
        echo ""
        echo "╔═══════════════════════════════════════════════════════════════╗"
        echo "║                    IMPORTANT NOTES                            ║"
        echo "╚═══════════════════════════════════════════════════════════════╝"
        echo ""
        echo -e "${YELLOW}This is a demo environment!${NC}"
        echo ""
        echo -e "• For real mDNS system setup: ${GREEN}isle mdns system install${NC}"
        echo -e "• For framework automation: ${GREEN}isle app init${NC}"
        echo -e "• For production apps: ${GREEN}isle app scaffold${NC}"
        echo ""
        echo "The sample environment is for:"
        echo "  ✓ Learning how Isle Mesh works"
        echo "  ✓ Testing mDNS concepts locally"
        echo "  ✓ Debugging and development"
        echo ""
        echo "NOT for:"
        echo "  ✗ Production deployments"
        echo "  ✗ Automated app generation"
        echo "  ✗ Real infrastructure setup"
        echo ""
        echo "╔═══════════════════════════════════════════════════════════════╗"
        echo "║                    RELATED COMMANDS                           ║"
        echo "╚═══════════════════════════════════════════════════════════════╝"
        echo ""
        echo "To set up real infrastructure:"
        echo -e "  • ${GREEN}isle mdns system install${NC}     Install mDNS system"
        echo -e "  • ${GREEN}isle app init${NC}                Create real app"
        echo -e "  • ${GREEN}isle mdns app up <app>${NC}       Run real app"
        echo ""
        echo -e "Back to overview: ${GREEN}isle mdns help${NC}"
        ;;
esac
