#!/bin/bash
# Script for managing sample/demo environments
# These are hand-crafted examples, not framework-generated

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the project root (parent of isle-cli)
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

SAMPLE_NAME=${1:-help}
shift # Remove the sample name from arguments
ACTION=${1:-help}

case $SAMPLE_NAME in
    localhost-mdns)
        # Delegate to localhost-mdns script
        LOCALHOST_MDNS_SCRIPT="$SCRIPT_DIR/localhost-mdns.sh"
        if [ ! -f "$LOCALHOST_MDNS_SCRIPT" ]; then
            echo "Error: localhost-mdns script not found"
            exit 1
        fi
        bash "$LOCALHOST_MDNS_SCRIPT" "$ACTION" "$@"
        ;;
    list)
        echo "Available sample environments:"
        echo ""
        echo "  localhost-mdns - Hand-crafted localhost mDNS demo environment"
        echo "                   (backend, frontend, proxy with mDNS)"
        echo ""
        echo "Usage: isle sample <name> [action]"
        echo "Example: isle sample localhost-mdns up"
        ;;
    help|*)
        echo "Isle Mesh Sample Environments"
        echo ""
        echo "Usage: isle sample <name> [action] [options]"
        echo ""
        echo "Sample environments are hand-crafted example projects that"
        echo "demonstrate Isle Mesh concepts. They are NOT generated by"
        echo "the framework automation."
        echo ""
        echo "Commands:"
        echo "  isle sample list              - List available sample environments"
        echo "  isle sample localhost-mdns    - Manage localhost-mdns demo"
        echo ""
        echo "Examples:"
        echo "  isle sample localhost-mdns up     # Start the demo"
        echo "  isle sample localhost-mdns logs   # View logs"
        echo "  isle sample localhost-mdns down   # Stop the demo"
        echo ""
        echo "For real Isle Mesh infrastructure setup, use:"
        echo "  isle mdns        - Configure real mDNS system"
        echo "  isle embed-jinja - Use framework automation"
        ;;
esac
