#!/usr/bin/env bash
# router-init.sh (bundled) — generated by pack.sh
# Edit sources under router-init-lib/ and router-init.main.sh
# -----------------------------------------------------------------------------
set -euo pipefail
BUNDLED_MODE=1

### ===== BEGIN LIBS =====

# --- 00-log.sh ---
#!/usr/bin/env bash
# BEGIN: 00-log.sh
if [[ -n "${_LOG_SH_SOURCED:-}" ]]; then return 0; fi; _LOG_SH_SOURCED=1

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'
log_info()    { echo -e "${BLUE}[INFO]${NC} $*" >&2; }
log_success() { echo -e "${GREEN}[✓]${NC} $*" >&2; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $*" >&2; }
log_error()   { echo -e "${RED}[✗]${NC} $*" >&2; }
log_step()    { echo >&2; echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" >&2; echo -e "${CYAN}  $*${NC}" >&2; echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" >&2; }
# END: 00-log.sh

# --- 10-args.sh ---
#!/usr/bin/env bash
# BEGIN: 10-args.sh
if [[ -n "${_ARGS_SH_SOURCED:-}" ]]; then return 0; fi; _ARGS_SH_SOURCED=1

parse_args() {
  while [[ $# -gt 0 ]]; do
    case $1 in
      --vm-name) VM_NAME="$2"; shift 2 ;;
      --memory)  MEMORY="$2"; shift 2 ;;
      --vcpus)   VCPUS="$2";  shift 2 ;;
      --image)   CUSTOM_IMAGE="$2"; shift 2 ;;
      --no-start) NO_START=true; shift ;;
      -h|--help)
        grep "^#" "${BASH_SOURCE[0]%/*}/../router-init.main.sh" | grep -v "#!/bin/bash" | sed 's/^# \?//'
        exit 0 ;;
      *) log_error "Unknown option: $1"; echo "Use --help for usage"; exit 1 ;;
    esac
  done
}
# END: 10-args.sh

# --- 15-ssh-key.sh ---
#!/usr/bin/env bash
# BEGIN: 15-ssh-key.sh
if [[ -n "${_SSH_KEY_SH_SOURCED:-}" ]]; then return 0; fi; _SSH_KEY_SH_SOURCED=1

# SSH key storage location
ISLE_SSH_DIR="${ISLE_SSH_DIR:-/etc/isle-mesh/router/ssh}"
ISLE_SSH_KEY="${ISLE_SSH_KEY:-$ISLE_SSH_DIR/isle_router_key}"
ISLE_SSH_PUB="${ISLE_SSH_PUB:-$ISLE_SSH_KEY.pub}"
ISLE_ROUTER_PASS_FILE="${ISLE_SSH_DIR}/.cached_password"

# SSH options to use the dedicated key
ISLE_SSH_OPTS="-i $ISLE_SSH_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

# Load cached router password (persisted across subprocesses)
if [[ -z "${ROUTER_PASSWORD:-}" ]] && [[ -f "$ISLE_ROUTER_PASS_FILE" ]]; then
  ROUTER_PASSWORD="$(cat "$ISLE_ROUTER_PASS_FILE" 2>/dev/null)"
fi

# Cache the router password so other scripts/subprocesses can reuse it
_cache_router_password() {
  local pass="$1"
  mkdir -p "$(dirname "$ISLE_ROUTER_PASS_FILE")"
  printf '%s' "$pass" > "$ISLE_ROUTER_PASS_FILE"
  chmod 600 "$ISLE_ROUTER_PASS_FILE"
}

# ── Central SSH/SCP helpers (try key, fall back to cached password) ──

# Run an SSH command to the router, handling auth automatically.
# Usage: router_ssh "command to run on router"
router_ssh() {
  local router_ip="${ROUTER_IP:-192.168.1.1}"
  local router_user="${ROUTER_USER:-root}"
  local base_opts="-o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  # Try key-based auth first (BatchMode prevents password prompt)
  if [[ -f "$ISLE_SSH_KEY" ]]; then
    if ssh -o BatchMode=yes $ISLE_SSH_OPTS "$base_opts" "${router_user}@${router_ip}" "$@" 2>/dev/null; then
      return 0
    fi
  fi

  # Fall back to cached password
  local cached_pass="${ROUTER_PASSWORD:-}"
  if [[ -z "$cached_pass" ]] && [[ -f "$ISLE_ROUTER_PASS_FILE" ]]; then
    cached_pass="$(cat "$ISLE_ROUTER_PASS_FILE" 2>/dev/null)"
  fi

  if [[ -n "$cached_pass" ]] && command -v sshpass >/dev/null 2>&1; then
    sshpass -p "$cached_pass" ssh $base_opts "${router_user}@${router_ip}" "$@"
    return $?
  fi

  # Last resort: plain ssh (will prompt interactively)
  ssh $base_opts "${router_user}@${router_ip}" "$@"
}

# SCP files to the router, handling auth automatically.
# Usage: router_scp <remote_dest> <local_file1> [local_file2 ...]
# Note: remote dest is FIRST arg so callers can pass expanded globs as remaining args.
router_scp() {
  local router_ip="${ROUTER_IP:-192.168.1.1}"
  local router_user="${ROUTER_USER:-root}"
  local remote_path="$1"
  shift
  local base_opts="-o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  # -O: use legacy SCP protocol (OpenWRT Dropbear lacks sftp-server)
  local scp_flags="-O"

  # Try key-based auth first
  if [[ -f "$ISLE_SSH_KEY" ]]; then
    if scp $scp_flags -o BatchMode=yes $ISLE_SSH_OPTS $base_opts "$@" "${router_user}@${router_ip}:${remote_path}" 2>/dev/null; then
      return 0
    fi
  fi

  # Fall back to cached password
  local cached_pass="${ROUTER_PASSWORD:-}"
  if [[ -z "$cached_pass" ]] && [[ -f "$ISLE_ROUTER_PASS_FILE" ]]; then
    cached_pass="$(cat "$ISLE_ROUTER_PASS_FILE" 2>/dev/null)"
  fi

  if [[ -n "$cached_pass" ]] && command -v sshpass >/dev/null 2>&1; then
    sshpass -p "$cached_pass" scp $scp_flags $base_opts "$@" "${router_user}@${router_ip}:${remote_path}"
    return $?
  fi

  # Last resort
  scp $scp_flags $base_opts "$@" "${router_user}@${router_ip}:${remote_path}"
}

# Test if we can reach the router via SSH (non-interactive, no prompts)
router_ssh_test() {
  local router_ip="${ROUTER_IP:-192.168.1.1}"
  local router_user="${ROUTER_USER:-root}"
  local base_opts="-o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  # Try key
  if [[ -f "$ISLE_SSH_KEY" ]]; then
    if ssh -o BatchMode=yes $ISLE_SSH_OPTS $base_opts "${router_user}@${router_ip}" "exit" 2>/dev/null; then
      return 0
    fi
  fi

  # Try cached password
  local cached_pass="${ROUTER_PASSWORD:-}"
  if [[ -z "$cached_pass" ]] && [[ -f "$ISLE_ROUTER_PASS_FILE" ]]; then
    cached_pass="$(cat "$ISLE_ROUTER_PASS_FILE" 2>/dev/null)"
  fi

  if [[ -n "$cached_pass" ]] && command -v sshpass >/dev/null 2>&1; then
    sshpass -p "$cached_pass" ssh $base_opts "${router_user}@${router_ip}" "exit" 2>/dev/null
    return $?
  fi

  return 1
}

# ── Key setup functions ──

setup_router_ssh_key() {
  log_step "Setting Up Dedicated SSH Key for Router Communication"

  # Create SSH directory if it doesn't exist
  if [[ ! -d "$ISLE_SSH_DIR" ]]; then
    log_info "Creating SSH key directory: $ISLE_SSH_DIR"
    sudo mkdir -p "$ISLE_SSH_DIR"
    sudo chmod 700 "$ISLE_SSH_DIR"
  fi

  # Check if key already exists
  if [[ -f "$ISLE_SSH_KEY" && -f "$ISLE_SSH_PUB" ]]; then
    log_success "SSH key already exists: $ISLE_SSH_KEY"

    # Verify key is valid
    if ssh-keygen -l -f "$ISLE_SSH_KEY" >/dev/null 2>&1; then
      log_success "Existing SSH key is valid"
      return 0
    else
      log_warning "Existing SSH key is invalid, regenerating..."
      sudo rm -f "$ISLE_SSH_KEY" "$ISLE_SSH_PUB"
    fi
  fi

  # Generate new SSH key (if-wrapped: the packed script runs under
  # set -e, so a bare command + $?-check dies before the check)
  log_info "Generating new SSH key for router communication..."
  if sudo ssh-keygen -t rsa -b 4096 -f "$ISLE_SSH_KEY" -N "" -C "isle-router-key" >/dev/null 2>&1; then
    log_success "SSH key generated: $ISLE_SSH_KEY"

    # Set proper permissions
    sudo chmod 600 "$ISLE_SSH_KEY"
    sudo chmod 644 "$ISLE_SSH_PUB"

    log_info "Public key fingerprint:"
    ssh-keygen -l -f "$ISLE_SSH_PUB" 2>/dev/null | sed 's/^/  /'
  else
    log_error "Failed to generate SSH key"
    exit 1
  fi
}

install_ssh_key_to_router() {
  local router_ip="${1:-192.168.1.1}"
  local router_user="${2:-root}"

  log_step "Installing SSH Key to OpenWRT Router"

  # Check if key exists
  if [[ ! -f "$ISLE_SSH_PUB" ]]; then
    log_error "SSH public key not found: $ISLE_SSH_PUB"
    log_info "Run setup_router_ssh_key first"
    return 1
  fi

  log_info "Router: ${router_user}@${router_ip}"

  # Read the public key
  local pub_key
  pub_key=$(sudo cat "$ISLE_SSH_PUB")

  local ssh_base_opts="-o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  # Require sshpass for non-interactive password auth
  if ! command -v sshpass >/dev/null 2>&1; then
    log_error "sshpass is required to install SSH key to router"
    log_info "Install with: sudo apt-get install sshpass"
    return 1
  fi

  local router_password="${ROUTER_PASSWORD:-}"
  local authenticated=false

  # Helper: test SSH with a given password (non-interactive)
  _try_ssh_pass() {
    sshpass -p "$1" ssh $ssh_base_opts "${router_user}@${router_ip}" "exit" 2>/dev/null
  }

  # If we have a cached/env password, try it first
  if [[ -n "$router_password" ]]; then
    log_info "Trying cached router password..."
    local max_attempts=10
    local attempt=0
    while [[ $attempt -lt $max_attempts ]]; do
      attempt=$((attempt + 1))
      if _try_ssh_pass "$router_password"; then
        authenticated=true
        break
      fi
      log_info "Waiting for router SSH (attempt $attempt/$max_attempts)..."
      sleep 3
    done
  fi

  # No cached password or it didn't work — prompt the user
  if [[ "$authenticated" != "true" ]]; then
    # Wait for SSH port to be reachable first
    log_info "Waiting for router SSH port..."
    local max_attempts=15
    local attempt=0
    while ! nc -z -w 2 "$router_ip" 22 2>/dev/null; do
      attempt=$((attempt + 1))
      if [[ $attempt -ge $max_attempts ]]; then
        log_error "Router SSH port not reachable after $max_attempts attempts"
        return 1
      fi
      sleep 3
    done

    # Non-interactive first: try the known default router password(s) so a standard install
    # needs no terminal. The isle OpenWRT image ships with a known default root password;
    # once in, the per-install key is installed and all later access is passwordless.
    local _dp
    for _dp in "${ROUTER_DEFAULT_PASSWORD:-root}" "root" ""; do
      if _try_ssh_pass "$_dp"; then
        router_password="$_dp"; authenticated=true
        log_info "Authenticated with default router password"
        break
      fi
    done

    # Fall back to a prompt ONLY if a real terminal is present. An app-invoked / unattended
    # install must never hang on stdin (zero-terminal goal).
    if [[ "$authenticated" != "true" ]]; then
      if [[ -t 0 ]]; then
        echo ""
        echo "  The OpenWRT router requires a password for initial SSH setup."
        echo "  This password will be cached and used to install an SSH key"
        echo "  so that subsequent connections are passwordless."
        echo ""
        echo -n "  Enter root password for router at ${router_ip}: "
        read -s router_password
        echo ""
        if _try_ssh_pass "$router_password"; then
          authenticated=true
        else
          log_error "SSH authentication failed with provided password"
          return 1
        fi
      else
        log_error "Router SSH auth failed (default rejected) and no terminal to prompt."
        log_info "Set ROUTER_PASSWORD env, or ensure the router image ships the default password."
        return 1
      fi
    fi
  fi

  # Cache the working password for other scripts in this session
  _cache_router_password "$router_password"
  ROUTER_PASSWORD="$router_password"
  log_success "SSH connection established"

  # Install the public key to BOTH Dropbear and OpenSSH locations
  # OpenWRT uses Dropbear which reads /etc/dropbear/authorized_keys
  log_info "Installing public key to router..."
  if sshpass -p "$router_password" ssh $ssh_base_opts \
      "${router_user}@${router_ip}" \
      "mkdir -p /etc/dropbear && \
       grep -qxF \"$pub_key\" /etc/dropbear/authorized_keys 2>/dev/null || \
       echo \"$pub_key\" >> /etc/dropbear/authorized_keys && \
       chmod 600 /etc/dropbear/authorized_keys" 2>/dev/null; then
    log_success "SSH key installed to router"
  else
    log_error "Failed to install SSH key to router"
    return 1
  fi

  # Verify key-based SSH works (BatchMode=yes prevents password fallback)
  log_info "Verifying key-based SSH..."
  if ssh -o BatchMode=yes $ISLE_SSH_OPTS -o ConnectTimeout=5 \
          "${router_user}@${router_ip}" "echo 'SSH_KEY_WORKS'" >/dev/null 2>&1; then
    log_success "Key-based SSH working"
  else
    log_warning "Key-based SSH verification failed — will use cached password for subsequent steps"
  fi
}

# Legacy helper functions (kept for compatibility, use router_ssh/router_scp instead)
ssh_router() {
  router_ssh "$@"
}

scp_router() {
  router_scp "$@"
}

# END: 15-ssh-key.sh

# --- 20-prereqs.sh ---
#!/usr/bin/env bash
# BEGIN: 20-prereqs.sh
if [[ -n "${_PREREQS_SH_SOURCED:-}" ]]; then return 0; fi; _PREREQS_SH_SOURCED=1

check_root() {
  if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
  fi
}

_detect_pkg_mgr() {
  command -v apt-get >/dev/null 2>&1 && { echo apt; return; }
  command -v dnf      >/dev/null 2>&1 && { echo dnf; return; }
  command -v yum      >/dev/null 2>&1 && { echo yum; return; }
  command -v pacman   >/dev/null 2>&1 && { echo pacman; return; }
  command -v zypper   >/dev/null 2>&1 && { echo zypper; return; }
  echo unknown
}

_sudo_prefix() {
  if [[ ${EUID:-$(id -u)} -eq 0 ]]; then echo ""
  elif command -v sudo >/dev/null 2>&1; then echo sudo
  else echo ""; fi
}

_try_install() {
  local mgr="$1"; shift
  local SUDO; SUDO=$(_sudo_prefix)
  case "$mgr" in
    apt)
      $SUDO apt-get update -y || return 1
      $SUDO env DEBIAN_FRONTEND=noninteractive apt-get install -y "$@" || return 1 ;;
    dnf|yum)
      $SUDO "$mgr" install -y "$@" || return 1 ;;
    pacman)
      $SUDO pacman -Sy --noconfirm "$@" || return 1 ;;
    zypper)
      $SUDO zypper --non-interactive refresh || true
      $SUDO zypper --non-interactive install "$@" || return 1 ;;
    *) return 1 ;;
  esac
}

_start_libvirt_service() {
  local SUDO; SUDO=$(_sudo_prefix)
  if [[ -n "$SUDO" ]]; then
    log_info "📋 You may be prompted for your password to enable libvirt service"
  fi
  if systemctl list-unit-files | grep -q '^libvirtd\.service'; then
    $SUDO systemctl enable --now libvirtd || true
  elif systemctl list-unit-files | grep -q '^libvirt\.service'; then
    $SUDO systemctl enable --now libvirt || true
  fi
  if ! systemctl is-active --quiet libvirtd 2>/dev/null && \
     ! systemctl is-active --quiet libvirt 2>/dev/null; then
    log_warning "libvirt service is not active."
  fi
}

check_prerequisites() {
  log_step "Step 1: Checking Prerequisites"

  local REQUIRED_CMDS=(virsh qemu-img wget ip setfacl getfacl yad sshpass)
  local missing=()

  for cmd in "${REQUIRED_CMDS[@]}"; do
    command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
  done

  if (( ${#missing[@]} )); then
    log_warning "Missing required commands: ${missing[*]}"
    local mgr; mgr="$(_detect_pkg_mgr)"
    if [[ "$mgr" == "unknown" ]]; then
      log_error "No supported package manager detected."
      log_info "Install manually: qemu-kvm qemu-system-x86 qemu-utils libvirt-daemon-system libvirt-clients bridge-utils wget acl yad sshpass"
      exit 1
    fi
    log_info "Attempting auto-install via $mgr…"
    log_info "📋 You may be prompted for your password to install required packages"
    if ! _try_install "$mgr" qemu-kvm qemu-system-x86 qemu-utils \
         libvirt-daemon-system libvirt-clients bridge-utils wget acl yad sshpass; then
      log_error "Automatic installation failed."
      [[ "$mgr" =~ dnf|yum ]] && log_info "Tip: enable EPEL if 'yad' is missing: sudo dnf install -y epel-release && sudo dnf install -y yad"
      log_info "Please install packages manually, then re-run."
      exit 1
    fi
  fi

  _start_libvirt_service
  log_success "All prerequisites installed and services checked"
}
# END: 20-prereqs.sh

# --- 30-perms.sh ---
#!/usr/bin/env bash
# BEGIN: 30-perms.sh
if [[ -n "${_PERMS_SH_SOURCED:-}" ]]; then return 0; fi; _PERMS_SH_SOURCED=1

setup_libvirt_permissions() {
  log_step "Step 2: Setting Up Libvirt Permissions"

  # Ensure IMAGE_DIR exists before setting ACLs
  mkdir -p "$IMAGE_DIR"

  local IMAGE_PATH="$IMAGE_DIR/openwrt-isle-router.qcow2"

  local LIBVIRT_USER="libvirt-qemu"
  if ! getent passwd "$LIBVIRT_USER" &> /dev/null; then
      if getent passwd "qemu" &> /dev/null; then
          LIBVIRT_USER="qemu"
      else
          log_error "Cannot find libvirt user (tried libvirt-qemu, qemu)"
          exit 1
      fi
  fi
  log_info "Using libvirt user: $LIBVIRT_USER"

  local CURRENT_PATH="$IMAGE_DIR"
  while [[ "$CURRENT_PATH" != "/" ]]; do
      if ! getfacl "$CURRENT_PATH" 2>/dev/null | grep -q "user:$LIBVIRT_USER"; then
          log_info "Granting traverse permission on $CURRENT_PATH"
          setfacl -m "u:$LIBVIRT_USER:x" "$CURRENT_PATH"
      fi
      CURRENT_PATH=$(dirname "$CURRENT_PATH")
  done

  if [[ -f "$IMAGE_PATH" ]]; then
      log_info "Granting read permission on $IMAGE_PATH"
      setfacl -m "u:$LIBVIRT_USER:r" "$IMAGE_PATH"
  fi

  log_success "Libvirt permissions configured using ACLs"
}
# END: 30-perms.sh

# --- 40-image.sh ---
#!/usr/bin/env bash
# BEGIN: 40-image.sh
if [[ -n "${_IMAGE_SH_SOURCED:-}" ]]; then return 0; fi; _IMAGE_SH_SOURCED=1

# The image is NOT shipped in git (see images/README.md). It is
# obtained by get-router-image.sh, which tries: local cache → the mesh
# → our public release → build from the upstream OpenWRT base.
#
# When running as the bundled router-init.sh, the sibling scripts may
# not be alongside us, so this keeps a self-contained build-from-
# upstream fallback — the same last resort the chain ends in.

_ROUTER_IMAGE_FALLBACK_VERSION="23.05.3"
_ROUTER_IMAGE_FALLBACK_SHA256="7643950cbf6bf5d785525f300efc4e2ceaad613b5d0725886e7f5fcc5a9d18f9"

# Inline last resort: fetch the upstream base, verify it, convert it.
_build_image_from_upstream() {
  local qcow2="$1"
  local version="$_ROUTER_IMAGE_FALLBACK_VERSION"
  local name="openwrt-${version}-x86-64-generic-ext4-combined.img.gz"
  local url="https://downloads.openwrt.org/releases/${version}/targets/x86/64/${name}"
  local compressed="$IMAGE_DIR/$name"
  local extracted="${compressed%.gz}"

  if [[ ! -f "$compressed" ]]; then
    log_info "Downloading OpenWRT ${version} base..."
    wget -q --show-progress -O "$compressed" "$url" || {
      log_error "Failed to download the upstream base"; rm -f "$compressed"; return 1; }
  fi

  # Refuse to build from a base we cannot vouch for.
  local got
  got="$(sha256sum "$compressed" | awk '{print $1}')"
  if [[ "$got" != "$_ROUTER_IMAGE_FALLBACK_SHA256" ]]; then
    log_error "Upstream base checksum mismatch — refusing to build"
    log_error "  expected $_ROUTER_IMAGE_FALLBACK_SHA256"
    log_error "  got      $got"
    return 1
  fi

  # Upstream's .gz has trailing padding: gunzip exits non-zero with
  # "trailing garbage ignored" on a good file, so judge by the result.
  log_info "Extracting base image..."
  gunzip -kf "$compressed" || true
  [[ -s "$extracted" ]] || { log_error "Extraction produced no image"; return 1; }

  log_info "Converting to qcow2..."
  qemu-img convert -f raw -O qcow2 "$extracted" "$qcow2" || return 1
  qemu-img resize "$qcow2" 4G >/dev/null || return 1
  rm -f "$extracted"
  return 0
}

download_image() {
  log_step "Step 3: Preparing OpenWRT Image"
  mkdir -p "$IMAGE_DIR"

  local QCOW2_IMAGE="$IMAGE_DIR/openwrt-isle-router.qcow2"

  if [[ -n "${CUSTOM_IMAGE:-}" ]]; then
    if [[ ! -f "$CUSTOM_IMAGE" ]]; then
      log_error "Custom image not found: $CUSTOM_IMAGE"; exit 1
    fi
    log_info "Using custom image: $CUSTOM_IMAGE"
    cp "$CUSTOM_IMAGE" "$QCOW2_IMAGE"
    log_success "Custom image copied"
    return
  fi

  if [[ -f "$QCOW2_IMAGE" ]]; then
    log_success "Image already exists: $QCOW2_IMAGE"
    return
  fi

  # Preferred: the full acquisition chain.
  local getter="${PROJECT_ROOT:-$SCRIPT_DIR}/get-router-image.sh"
  if [[ -x "$getter" ]]; then
    log_info "Obtaining router image (cache → mesh → release → build)..."
    if IMAGE_DIR="$IMAGE_DIR" "$getter" -o "$QCOW2_IMAGE"; then
      log_success "Image ready: $QCOW2_IMAGE"
      return
    fi
    log_warning "Acquisition chain failed — falling back to a direct upstream build"
  fi

  # Bundled/standalone: build from upstream directly.
  if _build_image_from_upstream "$QCOW2_IMAGE"; then
    log_success "Image ready: $QCOW2_IMAGE"
    return
  fi

  log_error "Could not obtain the router image"
  exit 1
}
# END: 40-image.sh

# --- 50-vm.sh ---
#!/usr/bin/env bash
# BEGIN: 50-vm.sh
if [[ -n "${_VM_SH_SOURCED:-}" ]]; then return 0; fi; _VM_SH_SOURCED=1

# Source template engine if not already loaded.
# This part runs from TWO homes: standalone at
# router-setup/router-init-lib/ (lib = ../../lib) and INLINED into the
# packed scripts/router-init.sh (lib = ./lib, a sibling subdir) — the
# 2026-08-19 fresh-box install died on the second shape. Try both.
if [[ -z "${_TEMPLATE_ENGINE_SH:-}" ]]; then
    _VM_HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
    if [[ -f "$_VM_HERE/lib/template-engine.sh" ]]; then
        LIB_DIR="$_VM_HERE/lib"
    else
        LIB_DIR="$(cd -- "$_VM_HERE/../../lib" && pwd)"
    fi
    source "$LIB_DIR/template-engine.sh"
fi

check_existing_vm() {
  if virsh list --all | grep -q "^.*\\b${VM_NAME}\\b"; then
    log_error "VM '${VM_NAME}' already exists!"
    log_info "Options:"
    log_info "  1. Use a different name: --vm-name other-name"
    log_info "  2. Destroy existing VM: virsh destroy ${VM_NAME} && virsh undefine ${VM_NAME}"
    exit 1
  fi
}

create_vm_xml() {
  log_step "Step 4: Creating VM Configuration"
  log_info "Configuring VM with br-mgmt (eth0) and isle-br-0 (eth1)..."

  local ROUTER_CONFIG_DIR="/etc/isle-mesh/router"
  mkdir -p "$ROUTER_CONFIG_DIR"

  local XML_FILE="$ROUTER_CONFIG_DIR/${VM_NAME}.xml"

  # Stage the router disk into the STANDARD libvirt images dir and run the VM from there.
  # The VM must NOT run from the install tree: virt-aa-helper (AppArmor) cannot read a disk
  # under /usr/share (the .deb bundle) or an arbitrary checkout path, so the per-VM AppArmor
  # profile fails to load and the VM won't start. Staging here makes the app (.deb) and cli
  # (checkout) installs behave IDENTICALLY — both run from /var/lib/libvirt/images.
  local TEMPLATE_IMAGE="$IMAGE_DIR/openwrt-isle-router.qcow2"
  local RUNTIME_DIR="/var/lib/libvirt/images"
  local IMAGE_PATH="$RUNTIME_DIR/${VM_NAME}.qcow2"
  mkdir -p "$RUNTIME_DIR"
  if [[ ! -f "$IMAGE_PATH" ]]; then
    log_info "Staging router image -> $IMAGE_PATH (writable, AppArmor-readable)"
    cp "$TEMPLATE_IMAGE" "$IMAGE_PATH" || { log_error "Failed to stage router image from $TEMPLATE_IMAGE"; exit 1; }
  fi
  chown libvirt-qemu:kvm "$IMAGE_PATH" 2>/dev/null || true
  chmod 660 "$IMAGE_PATH" 2>/dev/null || true

  # Use template engine to generate VM XML
  local vm_template
  vm_template=$(get_template "libvirt/base-vm.xml")

  apply_template "$vm_template" "$XML_FILE" \
    "VM_NAME=${VM_NAME}" \
    "MEMORY=${MEMORY}" \
    "VCPUS=${VCPUS}" \
    "IMAGE_PATH=${IMAGE_PATH}"

  log_success "VM configuration created: $XML_FILE"
  echo "$XML_FILE"
}

create_vm() {
  local XML_FILE="$1"
  log_step "Step 5: Creating VM"
  log_info "Defining VM '${VM_NAME}'..."
  virsh define "$XML_FILE" || { log_error "Failed to define VM"; exit 1; }
  log_success "VM '${VM_NAME}' created successfully"

  if [[ "${NO_START}" == "false" ]]; then
    log_info "Starting VM..."
    # Self-correcting start: on failure, remediate the two things that actually break a
    # router VM boot in normal use — a disk libvirt/AppArmor can't read (re-stage it into
    # the standard images dir) and a stale per-VM AppArmor profile (drop it, restart
    # libvirtd) — then retry once. Goal: the user never sees a raw libvirt error.
    if ! virsh start "$VM_NAME" 2>/dev/null; then
      log_warning "VM start failed — self-correcting (stage disk + clear stale AppArmor profile)..."
      local _rt="/var/lib/libvirt/images/${VM_NAME}.qcow2" _uuid
      [[ -f "$_rt" ]] || cp "$IMAGE_DIR/openwrt-isle-router.qcow2" "$_rt" 2>/dev/null || true
      chown libvirt-qemu:kvm "$_rt" 2>/dev/null || true; chmod 660 "$_rt" 2>/dev/null || true
      _uuid="$(virsh domuuid "$VM_NAME" 2>/dev/null)"
      [[ -n "$_uuid" ]] && rm -f "/etc/apparmor.d/libvirt/libvirt-${_uuid}"* 2>/dev/null || true
      systemctl restart libvirtd 2>/dev/null || true; sleep 2
      if virsh start "$VM_NAME" 2>/dev/null; then
        log_success "VM started (self-corrected)"
      else
        log_error "Failed to start VM after self-correction (see: journalctl -u libvirtd)"; exit 1
      fi
    else
      log_success "VM started"
    fi
    # always-available: bring the router up on libvirtd/boot, independent of boot-bringup
    virsh autostart "$VM_NAME" >/dev/null 2>&1 \
      && log_success "VM autostart enabled (always-available)" \
      || log_info "Could not set autostart (later: sudo virsh autostart ${VM_NAME})"
    log_info "Waiting for OpenWRT to boot (30 seconds)..."
    sleep 30
    log_success "OpenWRT should now be booted"
  else
    log_info "VM created but not started (--no-start specified)"
    log_info "Start with: sudo virsh start ${VM_NAME}"
  fi
}
# END: 50-vm.sh

# --- 60-bridge.sh ---
#!/bin/bash

#############################################################################
# Bridge Setup for OpenWRT Router
#
# Creates and configures two bridges:
#   - br-mgmt: Management bridge for SSH access to OpenWRT router
#   - isle-br-0: Isle bridge for local isle-agent connectivity
#
# This provides isolated management access and allows the local isle-agent
# container to connect to the router via DHCP
#############################################################################

# Create and configure management bridge
setup_management_bridge() {
    log_step "Management Bridge Setup"

    # Check for required commands
    if ! command -v ip &> /dev/null; then
        log_error "Missing required command: ip"
        log_info "Install with: apt-get install iproute2"
        return 1
    fi

    # Create br-mgmt bridge if it doesn't exist
    if ip link show br-mgmt &> /dev/null; then
        log_info "Bridge br-mgmt already exists"
    else
        log_info "Creating bridge: br-mgmt (Management network)"

        if ! ip link add br-mgmt type bridge; then
            log_error "Failed to create bridge br-mgmt"
            return 1
        fi

        if ! ip link set br-mgmt up; then
            log_error "Failed to bring up bridge br-mgmt"
            return 1
        fi

        log_success "Created bridge: br-mgmt"
    fi

    # Assign IP address to management bridge
    if ip addr show br-mgmt | grep -q "192.168.1.254"; then
        log_info "IP address already assigned to br-mgmt"
    else
        log_info "Assigning IP 192.168.1.254/24 to br-mgmt"

        if ! ip addr add 192.168.1.254/24 dev br-mgmt 2>/dev/null; then
            log_warning "IP address may already be assigned"
        fi
    fi

    # Enable IP forwarding
    sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1

    log_success "Management bridge configured (192.168.1.254/24)"
}

# Attach management bridge to VM
attach_management_bridge_to_vm() {
    log_info "Attaching br-mgmt to VM..."

    if [[ -z "$VM_NAME" ]]; then
        log_error "VM_NAME not set"
        return 1
    fi

    # Check if VM exists
    if ! virsh dominfo "$VM_NAME" &> /dev/null; then
        log_error "VM $VM_NAME does not exist"
        return 1
    fi

    # Check if management interface already exists
    if virsh dumpxml "$VM_NAME" | grep -q "br-mgmt"; then
        log_info "Management interface already attached to VM"
        return 0
    fi

    # Create temporary XML for network interface
    local INTERFACE_XML="/tmp/br-mgmt-interface.xml"
    cat > "$INTERFACE_XML" << 'EOF'
<interface type='bridge'>
  <source bridge='br-mgmt'/>
  <model type='virtio'/>
</interface>
EOF

    # Attach interface to VM
    if virsh attach-device "$VM_NAME" "$INTERFACE_XML" --config; then
        log_success "Management interface attached to VM"

        # If VM is running, attach to live config too
        if virsh domstate "$VM_NAME" | grep -q "running"; then
            virsh attach-device "$VM_NAME" "$INTERFACE_XML" --live &> /dev/null || true
            log_info "VM is running - reboot may be required for changes to take effect"
        fi
    else
        log_error "Failed to attach management interface to VM"
        rm -f "$INTERFACE_XML"
        return 1
    fi

    rm -f "$INTERFACE_XML"

    log_success "Management bridge attached to $VM_NAME"
}

# Create and configure isle-br-0 bridge for local agent
setup_isle_br_0() {
    log_step "Isle Bridge Setup (isle-br-0)"

    # Check for required commands
    if ! command -v ip &> /dev/null; then
        log_error "Missing required command: ip"
        log_info "Install with: apt-get install iproute2"
        return 1
    fi

    # Create isle-br-0 bridge if it doesn't exist
    if ip link show isle-br-0 &> /dev/null; then
        log_info "Bridge isle-br-0 already exists"
    else
        log_info "Creating bridge: isle-br-0 (Local isle agent connectivity)"

        if ! ip link add isle-br-0 type bridge; then
            log_error "Failed to create bridge isle-br-0"
            return 1
        fi

        if ! ip link set isle-br-0 up; then
            log_error "Failed to bring up bridge isle-br-0"
            return 1
        fi

        log_success "Created bridge: isle-br-0"
    fi

    # No IP address needed - OpenWRT will be the gateway
    # Docker macvlan will attach to this bridge

    log_success "Isle bridge configured (no IP - router will handle DHCP)"
}

# Attach isle-br-0 to VM as eth1
attach_isle_br_0_to_vm() {
    log_info "Attaching isle-br-0 to VM as eth1..."

    if [[ -z "$VM_NAME" ]]; then
        log_error "VM_NAME not set"
        return 1
    fi

    # Check if VM exists
    if ! virsh dominfo "$VM_NAME" &> /dev/null; then
        log_error "VM $VM_NAME does not exist"
        return 1
    fi

    # Check if isle-br-0 is already attached to VM
    if virsh dumpxml "$VM_NAME" | grep -q "isle-br-0"; then
        log_info "isle-br-0 already attached to VM"
        return 0
    fi

    # Create temporary XML for network interface
    local INTERFACE_XML="/tmp/isle-br-0-interface.xml"
    cat > "$INTERFACE_XML" << 'EOF'
<interface type='bridge'>
  <source bridge='isle-br-0'/>
  <model type='virtio'/>
</interface>
EOF

    # Attach interface to VM
    if virsh attach-device "$VM_NAME" "$INTERFACE_XML" --config; then
        log_success "isle-br-0 attached to VM (will be eth1)"

        # If VM is running, attach to live config too
        if virsh domstate "$VM_NAME" | grep -q "running"; then
            virsh attach-device "$VM_NAME" "$INTERFACE_XML" --live &> /dev/null || true
            log_info "VM is running - reboot may be required for eth1 to appear"
        fi
    else
        log_error "Failed to attach isle-br-0 to VM"
        rm -f "$INTERFACE_XML"
        return 1
    fi

    rm -f "$INTERFACE_XML"

    log_success "Isle bridge attached to $VM_NAME"
}

# Create bridges before VM creation (called early in init process)
create_bridges() {
    setup_management_bridge || return 1
    setup_isle_br_0 || return 1
    log_success "Both bridges created (br-mgmt and isle-br-0)"
}

# Verify bridges after VM creation (interfaces are already in VM template)
run_bridge_setup() {
    log_step "Verifying Network Configuration"

    # Verify bridges exist
    if ! ip link show br-mgmt &> /dev/null; then
        log_error "br-mgmt bridge not found - should have been created earlier"
        return 1
    fi

    if ! ip link show isle-br-0 &> /dev/null; then
        log_error "isle-br-0 bridge not found - should have been created earlier"
        return 1
    fi

    # Verify VM has both interfaces (they're in the template)
    local IFACE_COUNT
    IFACE_COUNT=$(virsh dumpxml "$VM_NAME" | grep -c "interface type" || echo 0)

    if [[ $IFACE_COUNT -lt 2 ]]; then
        log_error "VM should have 2 network interfaces, found: $IFACE_COUNT"
        log_info "This indicates the VM template may not have been applied correctly"
        return 1
    fi

    log_success "VM has $IFACE_COUNT network interfaces (br-mgmt + isle-br-0)"

    # Reboot the VM so OpenWRT can detect and configure both interfaces
    if virsh domstate "$VM_NAME" | grep -q "running"; then
        log_info "Rebooting VM to apply network configuration..."
        virsh reboot "$VM_NAME" &> /dev/null || {
            log_warning "Failed to reboot, trying shutdown and start..."
            virsh shutdown "$VM_NAME" --mode acpi &> /dev/null
            sleep 5
            virsh start "$VM_NAME" &> /dev/null || {
                log_error "Failed to restart VM"
                return 1
            }
        }
    fi

    log_info "Waiting for OpenWRT to boot and configure network (30 seconds)..."
    sleep 30

    # Verify connectivity
    if ping -c 1 -W 2 192.168.1.1 &> /dev/null; then
        log_success "OpenWRT is reachable at 192.168.1.1"
    else
        log_warning "Cannot ping 192.168.1.1 yet. You may need to wait longer or check VM console."
        log_info "Try: sudo virsh console $VM_NAME"
    fi

    return 0
}

# --- 70-download-packages.sh ---
#!/usr/bin/env bash
# BEGIN: 70-download-packages.sh
if [[ -n "${_DOWNLOAD_PACKAGES_SH_SOURCED:-}" ]]; then return 0; fi; _DOWNLOAD_PACKAGES_SH_SOURCED=1

# Download required OpenWRT packages for offline installation
OPENWRT_VERSION="${OPENWRT_VERSION:-23.05.3}"
ARCH="x86_64"
TARGET="x86/64"

# Required packages
# Note: kmod-8021q is built into the kernel for x86/64, no need to install
# Note: avahi-dbus-daemon provides the daemon functionality
REQUIRED_PACKAGES=(
  "avahi-dbus-daemon"
  "avahi-utils"
  "ip-full"
  "tcpdump"
)

# Function to download a single package and its dependencies
_download_package() {
  local pkg_name="$1"
  local found=false
  local packages_dir="$2"

  log_info "Searching for package: $pkg_name"

  # Base URLs for package repositories
  local base_url="https://downloads.openwrt.org/releases/${OPENWRT_VERSION}"
  local repos=(
    "$base_url/targets/${TARGET}/packages"
    "$base_url/packages/${ARCH}/base"
    "$base_url/packages/${ARCH}/packages"
    "$base_url/packages/${ARCH}/luci"
    "$base_url/packages/${ARCH}/routing"
  )

  for repo in "${repos[@]}"; do
    # Download Packages.gz to get package list
    local temp_pkg_list=$(mktemp)
    if curl -sf "${repo}/Packages.gz" | gunzip > "$temp_pkg_list" 2>/dev/null; then
      # Find package in the list
      local pkg_file=$(awk -v pkg="$pkg_name" '
        /^Package:/ { current_pkg = $2 }
        /^Filename:/ && current_pkg == pkg { print $2; exit }
      ' "$temp_pkg_list")

      if [[ -n "$pkg_file" ]]; then
        local pkg_filename=$(basename "$pkg_file")
        local download_url="${repo}/${pkg_file}"

        # Check if already downloaded
        if [[ -f "$packages_dir/$pkg_filename" ]]; then
          log_info "Already exists: $pkg_filename"
          found=true
        else
          log_info "Downloading from $repo"
          if curl -fL -o "$packages_dir/$pkg_filename" "$download_url"; then
            log_info "Downloaded: $pkg_filename"
            found=true
          else
            log_error "Failed to download: $download_url"
          fi
        fi

        # Get dependencies
        local deps=$(awk -v pkg="$pkg_name" '
          /^Package:/ { current_pkg = $2 }
          /^Depends:/ && current_pkg == pkg {
            gsub(/,/, " ", $0)
            sub(/^Depends: /, "", $0)
            print $0
          }
        ' "$temp_pkg_list")

        if [[ -n "$deps" ]]; then
          log_info "Dependencies for $pkg_name: $deps"
          # Download dependencies recursively (simple version - no version checks)
          for dep in $deps; do
            # Remove version constraints
            dep=$(echo "$dep" | sed 's/[>=<].*//; s/ //g')
            # Skip already processed or meta packages
            if [[ ! -f "$packages_dir"/*"${dep}"*.ipk ]] && [[ "$dep" != "libc" ]]; then
              _download_package "$dep" "$packages_dir"
            fi
          done
        fi

        rm -f "$temp_pkg_list"
        break
      fi
      rm -f "$temp_pkg_list"
    fi
  done

  if [[ "$found" == false ]]; then
    log_warning "Package not found: $pkg_name"
  fi
}

download_openwrt_packages() {
  log_step "Step 7: Downloading OpenWRT Packages"

  # Set packages directory relative to router-setup
  local script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  local packages_dir="${script_dir}/../packages"

  # Create packages directory
  mkdir -p "$packages_dir"

  log_info "OpenWRT Version: $OPENWRT_VERSION"
  log_info "Architecture: $ARCH"
  log_info "Packages directory: $packages_dir"

  for pkg in "${REQUIRED_PACKAGES[@]}"; do
    _download_package "$pkg" "$packages_dir"
  done

  log_success "Package download complete!"
  log_info "Downloaded packages are in: $packages_dir"

  # List downloaded packages
  local pkg_count=$(ls -1 "$packages_dir"/*.ipk 2>/dev/null | wc -l)
  if [[ $pkg_count -gt 0 ]]; then
    log_info "Downloaded $pkg_count package file(s)"
  else
    log_warning "No .ipk files found"
  fi
}
# END: 70-download-packages.sh

# --- 80-copy-packages.sh ---
#!/usr/bin/env bash
# BEGIN: 80-copy-packages.sh
if [[ -n "${_COPY_PACKAGES_SH_SOURCED:-}" ]]; then return 0; fi; _COPY_PACKAGES_SH_SOURCED=1

copy_packages_to_router() {
  log_step "Step 8: Copying Packages to Router VM"

  # Set packages directory relative to router-setup
  local script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  local packages_dir="${script_dir}/../packages"

  # Router connection details
  local router_dest="${ROUTER_PACKAGE_DIR:-/tmp/packages}"

  # Check if packages directory exists and has files
  if [[ ! -d "$packages_dir" ]]; then
    log_error "Packages directory not found: $packages_dir"
    exit 1
  fi

  local pkg_count=$(ls -1 "$packages_dir"/*.ipk 2>/dev/null | wc -l)
  if [[ $pkg_count -eq 0 ]]; then
    log_warning "No .ipk files found in $packages_dir"
    log_info "Skipping package copy"
    return 0
  fi

  log_info "Found $pkg_count package file(s) to copy"
  log_info "Destination: $router_dest"

  # Wait for SSH to be available
  log_info "Waiting for SSH connection to router..."
  local max_attempts=15
  local attempt=0
  while ! router_ssh_test; do
    attempt=$((attempt + 1))
    if [[ $attempt -ge $max_attempts ]]; then
      log_error "Failed to connect to router via SSH after $max_attempts attempts"
      exit 1
    fi
    sleep 2
  done
  log_success "SSH connection established"

  # Create destination directory on router
  log_info "Creating destination directory on router"
  if ! router_ssh "mkdir -p ${router_dest}"; then
    log_error "Failed to create directory on router"
    exit 1
  fi

  # Copy packages using SCP (glob expanded by shell before passing to function)
  log_info "Copying packages to router..."
  if router_scp "${router_dest}/" "$packages_dir"/*.ipk; then
    log_success "Successfully copied $pkg_count package(s) to router"

    # Verify files on router
    local remote_count
    remote_count=$(router_ssh "ls -1 ${router_dest}/*.ipk 2>/dev/null | wc -l") || remote_count=0
    log_info "Verified $remote_count file(s) on router"
  else
    log_error "Failed to copy packages to router"
    exit 1
  fi
}
# END: 80-copy-packages.sh

# --- 85-install-packages.sh ---
#!/usr/bin/env bash
# BEGIN: 85-install-packages.sh
if [[ -n "${_INSTALL_PACKAGES_SH_SOURCED:-}" ]]; then return 0; fi; _INSTALL_PACKAGES_SH_SOURCED=1

install_and_configure_packages() {
  log_step "Step 9: Installing and Configuring Packages on Router"

  local router_dest="${ROUTER_PACKAGE_DIR:-/tmp/packages}"

  # Check SSH connection
  if ! router_ssh_test; then
    log_error "Cannot connect to router via SSH"
    exit 1
  fi

  # Install packages
  log_info "Installing packages from ${router_dest}..."
  if router_ssh "opkg install ${router_dest}/*.ipk" 2>/dev/null; then
    log_success "Packages installed successfully"
  else
    log_warning "Some packages may have failed to install (this is often OK if already installed)"
  fi

  # Enable dbus FIRST (avahi requires it), then avahi. Both steps are
  # deliberately non-fatal — and must be WRITTEN that way: the packed
  # router-init.sh runs under `set -e`, so the old bare-command-then-
  # check-$? shape died silently on the first failure (the 2026-08-19
  # fresh-box run: this OpenWrt image's avahi has NO UCI section, so
  # `uci set avahi.@avahi[0]` was an instant fatal). Every remote step
  # sits in an if-condition, and the UCI path falls back to the conf
  # file avahi actually ships with.
  log_info "Enabling dbus service..."
  if router_ssh "/etc/init.d/dbus enable && /etc/init.d/dbus start" 2>/dev/null; then
    log_success "dbus service enabled and started"
  else
    log_warning "Failed to start dbus service"
  fi

  log_info "Configuring avahi-daemon..."
  if router_ssh \
      "uci -q set avahi.@avahi[0].enable_reflector='1' && \
       uci -q set avahi.@avahi[0].enable_dbus='yes' && \
       uci -q commit avahi" 2>/dev/null; then
    log_success "avahi configured via UCI"
  elif router_ssh \
      "[ -f /etc/avahi/avahi-daemon.conf ] && \
       sed -i 's/^#*enable-reflector=.*/enable-reflector=yes/' /etc/avahi/avahi-daemon.conf" 2>/dev/null; then
    log_success "avahi configured via /etc/avahi/avahi-daemon.conf (no UCI section on this image)"
  else
    log_warning "Failed to configure avahi-daemon (may need manual configuration)"
  fi
  if router_ssh "/etc/init.d/avahi-daemon enable && /etc/init.d/avahi-daemon restart" 2>/dev/null; then
    log_success "avahi-daemon enabled and started"
  else
    log_warning "avahi-daemon did not start (mDNS reflection degraded, not fatal)"
  fi

  # Verify services are running
  log_info "Verifying services..."
  local avahi_status
  avahi_status=$(router_ssh "/etc/init.d/avahi-daemon status" 2>/dev/null) || true

  if echo "$avahi_status" | grep -q "running"; then
    log_success "avahi-daemon is running"
  else
    log_warning "avahi-daemon may not be running properly"
  fi

  # Verify installed packages
  log_info "Verifying installed packages..."
  local installed_pkgs
  installed_pkgs=$(router_ssh "opkg list-installed | grep -cE '(avahi|ip-full|tcpdump)'" 2>/dev/null) || installed_pkgs=0

  log_info "Verified $installed_pkgs package(s) installed"

  log_success "Package installation and configuration complete"
}
# END: 85-install-packages.sh

# --- 90-next-steps.sh ---
#!/usr/bin/env bash
# BEGIN: 90-next-steps.sh
if [[ -n "${_NEXT_STEPS_SH_SOURCED:-}" ]]; then return 0; fi; _NEXT_STEPS_SH_SOURCED=1

show_next_steps() {
  log_step "Step 10: Router Initialization Complete!"

  echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║         OpenWRT Router VM Successfully Initialized            ║${NC}"
  echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
  echo
  echo -e "${BLUE}VM Information:${NC}"
  echo -e "  Name:              ${VM_NAME}"
  echo -e "  Status:            $(virsh list | grep -w "$VM_NAME" | awk '{print $3}' || echo "shut off")"
  echo -e "  Memory:            ${MEMORY} MB"
  echo -e "  vCPUs:             ${VCPUS}"
  echo
  echo -e "${BLUE}Network Bridges Created:${NC}"
  echo -e "  ${GREEN}✓${NC} br-mgmt     → eth0 (Management: 192.168.1.x)"
  echo -e "  ${GREEN}✓${NC} isle-br-0   → eth1 (Local isle-agent connectivity)"
  echo
  echo -e "${BLUE}Access Router:${NC}"
  echo -e "  SSH:               ssh root@192.168.1.1"
  echo -e "  Web Interface:     http://192.168.1.1"
  echo
  echo -e "${BLUE}Next Steps:${NC}"
  echo -e "  1) Configure Isle Network on Router:"
  echo -e "     ${GREEN}sudo isle router configure${NC}"
  echo -e "     ${GREEN}→ Sets up VLAN 10 on eth1 with DHCP for isle-agent${NC}"
  echo
  echo -e "  2) Start Local Isle Agent:"
  echo -e "     ${GREEN}cd isle-agent && docker-compose up -d${NC}"
  echo -e "     ${GREEN}→ Agent connects to router via isle-br-0${NC}"
  echo
  echo -e "  3) (Optional) Add External Interfaces:"
  echo -e "     ${GREEN}isle router add-connection${NC}"
  echo -e "     ${GREEN}→ Connect to external isles (isle-br-1, isle-br-2, etc.)${NC}"
  echo
  echo -e "  4) Check VM Status:"
  echo -e "     sudo virsh list"
  echo -e "     sudo virsh console ${VM_NAME}"
  echo
  echo -e "${BLUE}Docs:${NC}"
  echo -e "  - ISP Isolation Security: openwrt-router/docs/ISP-ISOLATION-SECURITY.md"
  echo -e "  - Router Management: isle-cli router --help"
  echo -e "  - Port Detection Service: systemctl status isle-port-detection"
  echo
}
# END: 90-next-steps.sh

### ===== END LIBS =====

# --- router-init.main.sh ---
#!/usr/bin/env bash
# router-init.main.sh — dev entrypoint (sources from router-init-lib/)
# The bundled version produced by pack.sh will NOT need to source anything.

set -euo pipefail

# Colors & logging may be used by main banner before libs load in bundle mode,
# so keep banner minimal here and leave colors to 00-log.sh
BUNDLED_MODE="${BUNDLED_MODE:-0}"

if [[ "$BUNDLED_MODE" != "1" ]]; then
  # Dev mode: source all libs in deterministic order
  SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  LIB_DIR="${SCRIPT_DIR}/router-init-lib"
  if [[ ! -d "$LIB_DIR" ]]; then
    echo "[ERR ] router-init-lib/ not found next to router-init.main.sh" >&2
    exit 1
  fi
  for f in "$LIB_DIR"/[0-9][0-9]-*.sh; do
    # shellcheck disable=SC1090
    source "$f"
  done
fi

# Runtime defaults (same as your current script)
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR" && pwd)"
VM_NAME="${VM_NAME:-openwrt-isle-router}"
MEMORY="${MEMORY:-512}"
VCPUS="${VCPUS:-2}"
IMAGE_DIR="${IMAGE_DIR:-$PROJECT_ROOT/images}"
NO_START=false
CUSTOM_IMAGE=""

main() {
  cat << EOF >&2
$(printf '%b' "${CYAN:-}")╔═══════════════════════════════════════════════════════════════╗
║       OpenWRT Router VM Creation (Step 1 of Isle Setup)      ║
║                                                                ║
║  • Creates OpenWRT VM                                         ║
║  • Configures br-mgmt (management) for SSH access             ║
║  • Configures isle-br-0 for local isle-agent connectivity     ║
║  • Isolated network: No external IP exposure                  ║
╚═══════════════════════════════════════════════════════════════╝$(printf '%b' "${NC:-}")
EOF

  parse_args "$@"
  check_root
  check_prerequisites
  check_existing_vm

  # Setup dedicated SSH key for router communication
  setup_router_ssh_key

  setup_libvirt_permissions
  download_image

  # Create bridges BEFORE VM creation (VM template references them)
  create_bridges

  local XML_FILE
  XML_FILE="$(create_vm_xml)"
  create_vm "$XML_FILE"

  # Verify network setup (interfaces already in VM template)
  run_bridge_setup

  download_openwrt_packages

  # Install SSH key BEFORE copying packages (key needed for SCP)
  install_ssh_key_to_router

  copy_packages_to_router

  install_and_configure_packages
  show_next_steps
  log_success "Initialization complete!"
}

if [[ "${BASH_SOURCE[0]:-}" == "$0" ]]; then
  main "$@"
fi
