FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
  dnsmasq \
  avahi-utils \
  iproute2 \
  iw \
  systemd \
  net-tools \
  curl \
  sudo \
  dnsutils \
  wpasupplicant \
  network-manager \
  util-linux \
  bash \
  && apt-get clean


COPY scripts/ /etc/isle-mesh/mdns/scripts/
COPY mesh-mdns.service /etc/isle-mesh/mdns/

RUN chmod +rx /etc/isle-mesh/mdns/scripts/*.sh

WORKDIR /etc/isle-mesh
ENTRYPOINT ["bash", "/etc/isle-mesh/mdns/scripts/check-isle-mesh-installed.sh"]