version: "3.9"

services:
  mesh-mdns-installer:
    build: .
    privileged: true
    network_mode: host
    volumes: # Bind to the existing files on the computer in their standardized locations, if they do not exist we copy our default files to them.
      - /etc:/etc
      - /usr/local/bin:/usr/local/bin
      - /etc/systemd/system:/etc/systemd/system
      - /lib/systemd/system:/lib/systemd/system
      - /run/systemd:/run/systemd
      - /etc/wpa_supplicant:/etc/wpa_supplicant
    restart: "no"
    container_name: mesh-mdns-installer